import { Navbar } from '@/components/shared/navbar'

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[var(--background)]">
      <Navbar backHref="/" backLabel="Home" />
      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="font-heading text-4xl mb-2">Terms of Service</h1>
        <p className="text-sm text-[var(--muted-foreground)] mb-10">Last updated: March 23, 2026</p>

        <div className="space-y-8 text-sm text-[var(--foreground)] leading-relaxed">
          <section>
            <h2 className="font-heading text-xl mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using Coursyx (&ldquo;the Service&rdquo;), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.</p>
          </section>

          <section>
            <h2 className="font-heading text-xl mb-3">2. Description of Service</h2>
            <p>Coursyx is an AI-powered course builder that helps users create educational content formatted for Skool communities. The Service allows users to upload source material (PDFs, YouTube links, URLs, or text) and generates course outlines, lessons, quizzes, video scripts, discussion prompts, and cover images.</p>
          </section>

          <section>
            <h2 className="font-heading text-xl mb-3">3. Account Registration</h2>
            <p>You must provide a valid email address and create a password to use the Service. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.</p>
          </section>

          <section>
            <h2 className="font-heading text-xl mb-3">4. Subscription Plans and Billing</h2>
            <p>Coursyx offers free and paid subscription plans. Paid plans are billed on a monthly or annual basis through our payment processor, Paddle. By subscribing to a paid plan, you authorize Paddle to charge your payment method at the agreed-upon intervals. You may also purchase individual course credits as one-time payments.</p>
          </section>

          <section>
            <h2 className="font-heading text-xl mb-3">5. Content Ownership</h2>
            <p>You retain all rights to the source material you upload. The courses generated by the Service using your source material belong to you. Coursyx does not claim ownership of any content you create or upload through the Service.</p>
          </section>

          <section>
            <h2 className="font-heading text-xl mb-3">6. Acceptable Use</h2>
            <p>You agree not to use the Service to: upload content you do not have the right to use; generate content that is illegal, harmful, or infringes on the rights of others; attempt to circumvent usage limits or security measures; resell or redistribute the Service itself without permission.</p>
          </section>

          <section>
            <h2 className="font-heading text-xl mb-3">7. AI-Generated Content</h2>
            <p>Content generated by the Service is produced by AI and may contain errors or inaccuracies. You are responsible for reviewing and editing all generated content before publishing or distributing it. Coursyx does not guarantee the accuracy, completeness, or suitability of any AI-generated content.</p>
          </section>

          <section>
            <h2 className="font-heading text-xl mb-3">8. Service Availability</h2>
            <p>Coursyx strives to maintain high availability but does not guarantee uninterrupted access. The Service may be temporarily unavailable due to maintenance, updates, or circumstances beyond our control.</p>
          </section>

          <section>
            <h2 className="font-heading text-xl mb-3">9. Termination</h2>
            <p>You may cancel your account at any time. Coursyx reserves the right to suspend or terminate accounts that violate these terms. Upon termination, your access to the Service will cease, but your existing course data will be retained for 30 days to allow data export.</p>
          </section>

          <section>
            <h2 className="font-heading text-xl mb-3">10. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, Coursyx and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the Service.</p>
          </section>

          <section>
            <h2 className="font-heading text-xl mb-3">11. Changes to Terms</h2>
            <p>Coursyx reserves the right to modify these terms at any time. We will notify users of significant changes via email or through the Service. Continued use of the Service after changes constitutes acceptance of the updated terms.</p>
          </section>

          <section>
            <h2 className="font-heading text-xl mb-3">12. Contact</h2>
            <p>For questions about these terms, contact us through the Help & Support form in your dashboard.</p>
          </section>
        </div>
      </div>
    </main>
  )
}
